[2022-10-28T13:31:49.432+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-28T13:31:34.670211+00:00 [queued]>
[2022-10-28T13:31:49.506+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-28T13:31:34.670211+00:00 [queued]>
[2022-10-28T13:31:49.507+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T13:31:49.507+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-28T13:31:49.507+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T13:31:49.644+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-28 13:31:34.670211+00:00
[2022-10-28T13:31:49.705+0000] {standard_task_runner.py:54} INFO - Started process 231 to run task
[2022-10-28T13:31:49.771+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-28T13:31:34.670211+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpvx8rmv3e']
[2022-10-28T13:31:49.773+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask processing_data
[2022-10-28T13:31:49.774+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-28T13:32:14.372+0000] {task_command.py:384} INFO - Running <TaskInstance: ml_pipeline.processing_data manual__2022-10-28T13:31:34.670211+00:00 [running]> on host 2ea3fe1dec9d
[2022-10-28T13:32:15.451+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Luka Perkovic
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T13:31:34.670211+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-28T13:31:34.670211+00:00
[2022-10-28T13:32:44.399+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/preprocess_data.py", line 41, in preprocess_data
    save_file(pd.DataFrame(data=scaler.fit_transform(df), columns=df.columns), 'data_batch_transformed.csv')
  File "/opt/airflow/dags/scripts/handle_file.py", line 23, in save_file
    df.to_csv(PATH)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/data_batch_transformed.csv'
[2022-10-28T13:32:44.499+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=processing_data, execution_date=20221028T133134, start_date=20221028T133149, end_date=20221028T133244
[2022-10-28T13:32:44.694+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 104 for task processing_data ([Errno 13] Permission denied: '/opt/airflow/data/data_batch_transformed.csv'; 231)
[2022-10-28T13:32:45.097+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-28T13:32:45.520+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
