[2022-10-27T13:43:14.353+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T13:43:03.680758+00:00 [queued]>
[2022-10-27T13:43:14.628+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T13:43:03.680758+00:00 [queued]>
[2022-10-27T13:43:14.628+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T13:43:14.628+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-27T13:43:14.628+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T13:43:14.868+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-27 13:43:03.680758+00:00
[2022-10-27T13:43:14.896+0000] {standard_task_runner.py:54} INFO - Started process 231 to run task
[2022-10-27T13:43:14.924+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-27T13:43:03.680758+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpbdvkwxg4']
[2022-10-27T13:43:14.943+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask processing_data
[2022-10-27T13:43:14.977+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T13:43:29.339+0000] {task_command.py:384} INFO - Running <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T13:43:03.680758+00:00 [running]> on host 52a93a57bc76
[2022-10-27T13:43:31.055+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Luka Perkovic
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T13:43:03.680758+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T13:43:03.680758+00:00
[2022-10-27T13:43:45.554+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/preprocess_data.py", line 18, in preprocess_data
    if validate_target_variable(df, 'train', target_variable='Cover_Type'):
  File "/opt/airflow/dags/scripts/validate_data.py", line 7, in validate_target_variable
    if type == 'train' and target_variable in df.columns:
AttributeError: 'str' object has no attribute 'columns'
[2022-10-27T13:43:45.672+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=processing_data, execution_date=20221027T134303, start_date=20221027T134314, end_date=20221027T134345
[2022-10-27T13:43:45.804+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task processing_data ('str' object has no attribute 'columns'; 231)
[2022-10-27T13:43:45.908+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-27T13:43:46.061+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
