[2022-10-27T14:47:44.354+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T14:47:35.947549+00:00 [queued]>
[2022-10-27T14:47:44.379+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T14:47:35.947549+00:00 [queued]>
[2022-10-27T14:47:44.380+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T14:47:44.380+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-27T14:47:44.381+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T14:47:44.427+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-27 14:47:35.947549+00:00
[2022-10-27T14:47:44.442+0000] {standard_task_runner.py:54} INFO - Started process 291 to run task
[2022-10-27T14:47:44.453+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-27T14:47:35.947549+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp6_mhcki_']
[2022-10-27T14:47:44.459+0000] {standard_task_runner.py:83} INFO - Job 67: Subtask processing_data
[2022-10-27T14:47:44.468+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T14:47:50.094+0000] {task_command.py:384} INFO - Running <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T14:47:35.947549+00:00 [running]> on host 248b4129bb61
[2022-10-27T14:47:50.266+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Luka Perkovic
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T14:47:35.947549+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T14:47:35.947549+00:00
[2022-10-27T14:48:03.195+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/preprocess_data.py", line 41, in preprocess_data
    save_file(scaler.fit_transform(df), 'data_batch_transformed.csv')
  File "/opt/airflow/dags/scripts/handle_file.py", line 20, in save_file
    df.to_csv(os.path.join(DATA_DIR, file_name))
AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'
[2022-10-27T14:48:03.243+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=processing_data, execution_date=20221027T144735, start_date=20221027T144744, end_date=20221027T144803
[2022-10-27T14:48:03.331+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 67 for task processing_data ('numpy.ndarray' object has no attribute 'to_csv'; 291)
[2022-10-27T14:48:03.380+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-27T14:48:03.519+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
