[2022-10-27T15:09:08.960+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T15:04:57.310274+00:00 [queued]>
[2022-10-27T15:09:08.992+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T15:04:57.310274+00:00 [queued]>
[2022-10-27T15:09:09.012+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T15:09:09.013+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 1
[2022-10-27T15:09:09.013+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T15:09:09.071+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-27 15:04:57.310274+00:00
[2022-10-27T15:09:09.088+0000] {standard_task_runner.py:54} INFO - Started process 172 to run task
[2022-10-27T15:09:09.122+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-27T15:04:57.310274+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp3gzjvei5']
[2022-10-27T15:09:09.190+0000] {standard_task_runner.py:83} INFO - Job 74: Subtask processing_data
[2022-10-27T15:09:09.191+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T15:09:13.527+0000] {task_command.py:384} INFO - Running <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T15:04:57.310274+00:00 [running]> on host 515fdaad0015
[2022-10-27T15:09:13.879+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Luka Perkovic
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T15:04:57.310274+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T15:04:57.310274+00:00
[2022-10-27T15:09:18.394+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/preprocess_data.py", line 41, in preprocess_data
    save_file(pd.DataFrame(data=scaler.fit_transform(df), columns=df.columns), 'data_batch_transformed.csv')
NameError: name 'pd' is not defined
[2022-10-27T15:09:18.415+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=processing_data, execution_date=20221027T150457, start_date=20221027T150908, end_date=20221027T150918
[2022-10-27T15:09:18.432+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 74 for task processing_data (name 'pd' is not defined; 172)
[2022-10-27T15:09:18.463+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-27T15:09:18.519+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
