[2022-10-27T16:44:18.903+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T16:44:09.444525+00:00 [queued]>
[2022-10-27T16:44:19.011+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T16:44:09.444525+00:00 [queued]>
[2022-10-27T16:44:19.011+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T16:44:19.012+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-27T16:44:19.012+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T16:44:19.137+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-27 16:44:09.444525+00:00
[2022-10-27T16:44:19.178+0000] {standard_task_runner.py:54} INFO - Started process 207 to run task
[2022-10-27T16:44:19.185+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-27T16:44:09.444525+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp55by283p']
[2022-10-27T16:44:19.207+0000] {standard_task_runner.py:83} INFO - Job 84: Subtask processing_data
[2022-10-27T16:44:19.208+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T16:44:24.178+0000] {task_command.py:384} INFO - Running <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T16:44:09.444525+00:00 [running]> on host 7e36d366ff8a
[2022-10-27T16:44:24.494+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Luka Perkovic
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T16:44:09.444525+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T16:44:09.444525+00:00
[2022-10-27T16:44:38.403+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/preprocess_data.py", line 41, in preprocess_data
    save_file(pd.DataFrame(data=scaler.fit_transform(df), columns=df.columns), 'data_batch_transformed.csv')
  File "/opt/airflow/dags/scripts/handle_file.py", line 20, in save_file
    df.to_csv(os.path.join(DATA_DIR, file_name))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/data_batch_transformed.csv'
[2022-10-27T16:44:38.437+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=processing_data, execution_date=20221027T164409, start_date=20221027T164418, end_date=20221027T164438
[2022-10-27T16:44:38.453+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 84 for task processing_data ([Errno 13] Permission denied: '/opt/airflow/data/data_batch_transformed.csv'; 207)
[2022-10-27T16:44:38.514+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-27T16:44:38.597+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
